# Classify HFpEF

In [1]:
import pandas as pd
import numpy as np

from preproc import get_hfpef_100, get_hfpef_100_nomiss_selected_feats, convert2np

In [2]:
lbl_colname= ['Death', 'CV death', 'HF hospitalization']

## Clean Data

In [3]:
data_df = get_hfpef_100()

In [4]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 98 entries, 0 to 99
Data columns (total 45 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 98 non-null     int64
 1   Sex                 98 non-null     int64
 2   Cr                  98 non-null     float64
 3   GFR                 98 non-null     float64
 4   CKD stage           98 non-null     int64
 5   smoke               98 non-null     float64
 6   BMI                 98 non-null     float64
 7   DM                  98 non-null     int64
 8   Insulin             98 non-null     int64
 9   AF                  98 non-null     int64
 10  SBP                 98 non-null     float64
 11  DBP                 98 non-null     float64
 12  MAP                 98 non-null     float64
 13  PP                  98 non-null     int64
 14  HR                  98 non-null     float64
 15  ACE-i               98 non-null     int64
 16  ARB                 98 non-null     int64
 17  ARNI                98 non-null     int64
 18  betablocker         98 non-null     int64
 19  Aspirin             98 non-null     int64
 20  SGLT2i              98 non-null     int64
 21  MRA                 98 non-null     int64
 22  MI                  98 non-null     int64
 23  stroke              98 non-null     float64
 24  COPD                98 non-null     int64
 25  NYHA                98 non-null     int64
 26  edema               98 non-null     int64
 27  SSRI                98 non-null     int64
 28  Death               98 non-null     int64
 29  CV death            98 non-null     int64
 30  HF hospitalization  98 non-null     int64
 31  NTProBNP            98 non-null     float64
 32  medial a'           98 non-null     float64
 33  medial E'           98 non-null     float64
 34  lateral E'          98 non-null     float64
 35  e/E'                98 non-null     float64
 36  lateral e/E'        98 non-null     float64
 37  E/A                 98 non-null     float64
 38  Mitral E/e'         98 non-null     float64
 39  TR Vmax             98 non-null     float64
 40  RWT                 98 non-null     float64
 41  LV mass index       98 non-null     float64
 42  LAVI                98 non-null     float64
 43  LA diameter         98 non-null     float64
 44  LVEF                98 non-null     float64
dtypes: float64(23), int64(22)
memory usage: 35.2 KB

In [5]:
data_df.describe()

,Age,Sex,Cr,GFR,CKD stage,smoke,BMI,DM,Insulin,AF,...,e/E',lateral e/E',E/A,Mitral E/e',TR Vmax,RWT,LV mass index,LAVI,LA diameter,LVEF
count,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,...,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000
mean,71.959184,1.663265,1.785408,50.869592,2.846939,0.132653,21.114286,0.581633,0.316327,0.367347,...,14.155561,12.738469,0.782552,16.743163,2.015612,0.698551,115.998878,27.176531,2.545612,62.105102
std,11.604228,0.475023,1.570997,26.728925,1.096875,0.340943,11.354485,0.495827,0.467433,0.484561,...,7.488935,6.640708,0.691967,8.067268,1.439859,0.422547,53.494470,26.203525,2.147586,7.225176
min,34.000000,1.000000,0.550000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000
25%,65.000000,1.000000,0.892500,27.250000,2.000000,0.000000,18.700000,0.000000,0.000000,0.000000,...,9.812500,8.625000,0.500000,11.800000,0.000000,0.432500,85.075000,0.000000,0.000000,56.000000
50%,74.000000,2.000000,1.170000,52.000000,3.000000,0.000000,23.300000,1.000000,0.000000,0.000000,...,13.615000,12.150000,0.700000,16.300000,2.575000,0.580000,113.850000,28.050000,3.600000,61.250000
75%,79.000000,2.000000,1.982500,68.750000,4.000000,0.000000,28.475000,1.000000,1.000000,1.000000,...,18.825000,16.575000,1.000000,20.850000,3.040000,0.900000,138.905000,44.725000,4.400000,67.300000
max,97.000000,2.000000,10.000000,105.000000,5.000000,1.000000,45.000000,1.000000,1.000000,1.000000,...,33.750000,30.700000,4.100000,42.200000,4.550000,2.300000,356.600000,107.700000,6.000000,80.000000

## Get Cleaned Data

In [6]:
data_df_clean = get_hfpef_100_nomiss_selected_feats()

In [8]:
data_df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51 entries, 1 to 97
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 51 non-null     int64
 1   Sex                 51 non-null     int64
 2   Cr                  51 non-null     float64
 3   GFR                 51 non-null     float64
 4   CKD stage           51 non-null     int64
 5   AF                  51 non-null     int64
 6   MAP                 51 non-null     float64
 7   PP                  51 non-null     int64
 8   NTProBNP            51 non-null     float64
 9   medial a'           51 non-null     float64
 10  medial E'           51 non-null     float64
 11  LAVI                51 non-null     float64
 12  LA diameter         51 non-null     float64
 13  Death               51 non-null     int64
 14  CV death            51 non-null     int64
 15  HF hospitalization  51 non-null     int64
dtypes: float64(8), int64(8)
memory usage: 6.8 KB

In [9]:
data_df_clean.describe()

,Age,Sex,Cr,GFR,CKD stage,AF,MAP,PP,NTProBNP,medial a',medial E',LAVI,LA diameter,Death,CV death,HF hospitalization
count,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000
mean,72.235294,1.627451,2.000980,50.958431,2.862745,0.215686,93.490196,71.764706,9129.700784,7.794118,5.083333,29.774510,2.411765,0.176471,0.078431,0.627451
std,11.885433,0.488294,1.922055,29.636126,1.249314,0.415390,10.019393,19.344858,11348.285521,2.668111,1.659339,24.976924,2.109848,0.385013,0.271524,0.488294
min,34.000000,1.000000,0.630000,2.000000,1.000000,0.000000,70.000000,25.000000,41.740000,2.020000,2.760000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,67.000000,1.000000,0.875000,22.000000,2.000000,0.000000,87.500000,60.000000,1174.500000,6.220000,3.685000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,75.000000,2.000000,1.130000,58.000000,3.000000,0.000000,94.333333,69.000000,3493.000000,7.770000,4.760000,30.900000,3.500000,0.000000,0.000000,1.000000
75%,78.500000,2.000000,2.225000,73.000000,4.000000,0.000000,100.000000,81.500000,12887.000000,9.870000,6.290000,42.100000,4.100000,0.000000,0.000000,1.000000
max,92.000000,2.000000,10.000000,105.000000,5.000000,1.000000,117.000000,124.000000,35001.000000,12.800000,9.160000,107.700000,6.000000,1.000000,1.000000,1.000000

## Random Forest

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import cross_val_score, cross_val_predict, cross_validate 
from sklearn.metrics import classification_report

In [11]:
def hfpef_rf(X, y, feature_list):
    # Set the parameters by cross-validation
    tuned_parameters = [{'max_depth': [5,10,20],
                         'n_estimators': [100, 200, 400]}]

    rf = RandomForestClassifier(random_state=0)

    for i in range(y.shape[1]):
        print('==================================================')
        print('Prediction of ' + lbl_colname[i])

        y_true = y[:,i]

        clf = GridSearchCV(rf, tuned_parameters, scoring='f1_macro', cv=5)
        clf.fit(X, y_true)

        print("Best parameters set found on development set:")
        print()
        print(clf.best_params_)
        print()
        print("Grid scores on development set:")
        print()
        means = clf.cv_results_['mean_test_score']
        stds = clf.cv_results_['std_test_score']
        for mean, std, params in zip(means, stds, clf.cv_results_['params']):
            print("%0.3f (+/-%0.03f) for %r"
                  % (mean, std * 2, params))
        print()

        y_pred = cross_val_predict(clf.best_estimator_, X, y_true, cv=5)

        print(f"count {sum(y_pred)}/{len(y_pred)}")
        print("Detailed classification report:")
        print()
        print(classification_report(y_true, y_pred))
        print()

        for i,v in sorted(zip(feature_list, clf.best_estimator_.feature_importances_), key=lambda tup: tup[1], reverse=True)[:20]:
            print('Feature: %s, Score: %.5f' % (i,v))

### All Features

In [12]:
X, y, feature_list = convert2np(data_df, lbl_colname)

In [13]:
hfpef_rf(X, y, feature_list)

==================================================
Prediction of Death
Best parameters set found on development set:

{'max_depth': 5, 'n_estimators': 400}

Grid scores on development set:

0.417 (+/-0.017) for {'max_depth': 5, 'n_estimators': 100}
0.427 (+/-0.019) for {'max_depth': 5, 'n_estimators': 200}
0.430 (+/-0.011) for {'max_depth': 5, 'n_estimators': 400}
0.420 (+/-0.026) for {'max_depth': 10, 'n_estimators': 100}
0.420 (+/-0.032) for {'max_depth': 10, 'n_estimators': 200}
0.427 (+/-0.019) for {'max_depth': 10, 'n_estimators': 400}
0.420 (+/-0.026) for {'max_depth': 20, 'n_estimators': 100}
0.420 (+/-0.032) for {'max_depth': 20, 'n_estimators': 200}
0.427 (+/-0.019) for {'max_depth': 20, 'n_estimators': 400}

count 0/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.76      1.00      0.86        74
           1       0.00      0.00      0.00        24

    accuracy                           0.76        98
   macro avg       0.38      0.50      0.43        98
weighted avg       0.57      0.76      0.65        98


Feature: HR, Score: 0.06111
Feature: TR Vmax, Score: 0.05143
Feature: Cr, Score: 0.04665
Feature: LA diameter, Score: 0.04627
Feature: GFR, Score: 0.04488
Feature: BMI, Score: 0.04250
Feature: E/A, Score: 0.04097
Feature: RWT, Score: 0.04059
Feature: LVEF, Score: 0.04019
Feature: stroke, Score: 0.03980
Feature: LV mass index, Score: 0.03820
Feature: medial a', Score: 0.03668
Feature: SBP, Score: 0.03597
Feature: lateral E', Score: 0.03354
Feature: medial E', Score: 0.03341
Feature: Age, Score: 0.03274
Feature: lateral e/E', Score: 0.03273
Feature: DBP, Score: 0.03080
Feature: LAVI, Score: 0.03073
Feature: NTProBNP, Score: 0.02931
==================================================
Prediction of CV death

C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best parameters set found on development set:

{'max_depth': 5, 'n_estimators': 100}

Grid scores on development set:

0.479 (+/-0.013) for {'max_depth': 5, 'n_estimators': 100}
0.479 (+/-0.013) for {'max_depth': 5, 'n_estimators': 200}
0.479 (+/-0.013) for {'max_depth': 5, 'n_estimators': 400}
0.479 (+/-0.013) for {'max_depth': 10, 'n_estimators': 100}
0.479 (+/-0.013) for {'max_depth': 10, 'n_estimators': 200}
0.479 (+/-0.013) for {'max_depth': 10, 'n_estimators': 400}
0.479 (+/-0.013) for {'max_depth': 20, 'n_estimators': 100}
0.479 (+/-0.013) for {'max_depth': 20, 'n_estimators': 200}
0.479 (+/-0.013) for {'max_depth': 20, 'n_estimators': 400}

count 0/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        90
           1       0.00      0.00      0.00         8

    accuracy                           0.92        98
   macro avg       0.46      0.50      0.48        98
weighted avg       0.84      0.92      0.88        98


Feature: TR Vmax, Score: 0.07803
Feature: lateral E', Score: 0.06615
Feature: Age, Score: 0.06248
Feature: e/E', Score: 0.05174
Feature: RWT, Score: 0.05083
Feature: BMI, Score: 0.04667
Feature: LA diameter, Score: 0.04384
Feature: LV mass index, Score: 0.04282
Feature: stroke, Score: 0.03686
Feature: Mitral E/e', Score: 0.03577
Feature: medial E', Score: 0.03549
Feature: HR, Score: 0.03381
Feature: lateral e/E', Score: 0.03161
Feature: GFR, Score: 0.03020
Feature: smoke, Score: 0.02956
Feature: LVEF, Score: 0.02837
Feature: LAVI, Score: 0.02669
Feature: NTProBNP, Score: 0.02662
Feature: DBP, Score: 0.02537
Feature: PP, Score: 0.02522
==================================================
Prediction of HF hospitalization

C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best parameters set found on development set:

{'max_depth': 10, 'n_estimators': 200}

Grid scores on development set:

0.596 (+/-0.150) for {'max_depth': 5, 'n_estimators': 100}
0.573 (+/-0.209) for {'max_depth': 5, 'n_estimators': 200}
0.592 (+/-0.168) for {'max_depth': 5, 'n_estimators': 400}
0.597 (+/-0.107) for {'max_depth': 10, 'n_estimators': 100}
0.599 (+/-0.186) for {'max_depth': 10, 'n_estimators': 200}
0.597 (+/-0.158) for {'max_depth': 10, 'n_estimators': 400}
0.597 (+/-0.107) for {'max_depth': 20, 'n_estimators': 100}
0.599 (+/-0.186) for {'max_depth': 20, 'n_estimators': 200}
0.597 (+/-0.158) for {'max_depth': 20, 'n_estimators': 400}

count 72/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.62      0.39      0.48        41
           1       0.65      0.82      0.73        57

    accuracy                           0.64        98
   macro avg       0.63      0.61      0.60        98
weighted avg       0.64      0.64      0.62        98


Feature: NTProBNP, Score: 0.07145
Feature: medial E', Score: 0.06380
Feature: Mitral E/e', Score: 0.05443
Feature: RWT, Score: 0.04817
Feature: Cr, Score: 0.04506
Feature: Age, Score: 0.04212
Feature: LA diameter, Score: 0.04132
Feature: GFR, Score: 0.03883
Feature: LVEF, Score: 0.03836
Feature: E/A, Score: 0.03490
Feature: e/E', Score: 0.03485
Feature: SBP, Score: 0.03385
Feature: PP, Score: 0.03313
Feature: medial a', Score: 0.03152
Feature: BMI, Score: 0.03108
Feature: LV mass index, Score: 0.03045
Feature: TR Vmax, Score: 0.03040
Feature: DBP, Score: 0.02993
Feature: lateral E', Score: 0.02862
Feature: lateral e/E', Score: 0.02771

### Selected Features

In [14]:
X, y, feature_list = convert2np(data_df, lbl_colname, selected_feat=True)

In [15]:
hfpef_rf(X, y, feature_list)

==================================================
Prediction of Death
Best parameters set found on development set:

{'max_depth': 10, 'n_estimators': 100}

Grid scores on development set:

0.436 (+/-0.135) for {'max_depth': 5, 'n_estimators': 100}
0.412 (+/-0.031) for {'max_depth': 5, 'n_estimators': 200}
0.412 (+/-0.031) for {'max_depth': 5, 'n_estimators': 400}
0.440 (+/-0.127) for {'max_depth': 10, 'n_estimators': 100}
0.409 (+/-0.027) for {'max_depth': 10, 'n_estimators': 200}
0.416 (+/-0.034) for {'max_depth': 10, 'n_estimators': 400}
0.440 (+/-0.127) for {'max_depth': 20, 'n_estimators': 100}
0.409 (+/-0.027) for {'max_depth': 20, 'n_estimators': 200}
0.416 (+/-0.034) for {'max_depth': 20, 'n_estimators': 400}

count 7/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.75      0.92      0.82        74
           1       0.14      0.04      0.06        24

    accuracy                           0.70        98
   macro avg       0.45      0.48      0.44        98
weighted avg       0.60      0.70      0.64        98


Feature: MAP, Score: 0.10659
Feature: LA diameter, Score: 0.10499
Feature: GFR, Score: 0.10452
Feature: Cr, Score: 0.10291
Feature: medial a', Score: 0.09040
Feature: NTProBNP, Score: 0.08960
Feature: Age, Score: 0.08944
Feature: medial E', Score: 0.08699
Feature: PP, Score: 0.07282
Feature: LAVI, Score: 0.06372
Feature: CKD stage, Score: 0.04654
Feature: AF, Score: 0.02438
Feature: Sex, Score: 0.01712
==================================================
Prediction of CV death
Best parameters set found on development set:

{'max_depth': 5, 'n_estimators': 100}

Grid scores on development set:

0.479 (+/-0.013) for {'max_depth': 5, 'n_estimators': 100}
0.479 (+/-0.013) for {'max_depth': 5, 'n_estimators': 200}
0.479 (+/-0.013) for {'max_depth': 5, 'n_estimators': 400}
0.479 (+/-0.013) for {'max_depth': 10, 'n_estimators': 100}
0.479 (+/-0.013) for {'max_depth': 10, 'n_estimators': 200}
0.479 (+/-0.013) for {'max_depth': 10, 'n_estimators': 400}
0.479 (+/-0.013) for {'max_depth': 20, 'n_estimators': 100}
0.479 (+/-0.013) for {'max_depth': 20, 'n_estimators': 200}
0.479 (+/-0.013) for {'max_depth': 20, 'n_estimators': 400}

count 0/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        90
           1       0.00      0.00      0.00         8

    accuracy                           0.92        98
   macro avg       0.46      0.50      0.48        98
weighted avg       0.84      0.92      0.88        98


Feature: Age, Score: 0.16413
Feature: LA diameter, Score: 0.12178
Feature: medial E', Score: 0.11328
Feature: NTProBNP, Score: 0.10028
Feature: GFR, Score: 0.08962
Feature: Cr, Score: 0.08803
Feature: PP, Score: 0.08416
Feature: medial a', Score: 0.07293
Feature: MAP, Score: 0.06332
Feature: LAVI, Score: 0.05601
Feature: CKD stage, Score: 0.02709
Feature: AF, Score: 0.01536
Feature: Sex, Score: 0.00402
==================================================
Prediction of HF hospitalization

C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best parameters set found on development set:

{'max_depth': 5, 'n_estimators': 400}

Grid scores on development set:

0.567 (+/-0.151) for {'max_depth': 5, 'n_estimators': 100}
0.587 (+/-0.150) for {'max_depth': 5, 'n_estimators': 200}
0.609 (+/-0.160) for {'max_depth': 5, 'n_estimators': 400}
0.590 (+/-0.149) for {'max_depth': 10, 'n_estimators': 100}
0.577 (+/-0.159) for {'max_depth': 10, 'n_estimators': 200}
0.598 (+/-0.230) for {'max_depth': 10, 'n_estimators': 400}
0.590 (+/-0.149) for {'max_depth': 20, 'n_estimators': 100}
0.577 (+/-0.159) for {'max_depth': 20, 'n_estimators': 200}
0.598 (+/-0.230) for {'max_depth': 20, 'n_estimators': 400}

count 68/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.60      0.44      0.51        41
           1       0.66      0.79      0.72        57

    accuracy                           0.64        98
   macro avg       0.63      0.61      0.61        98
weighted avg       0.64      0.64      0.63        98


Feature: NTProBNP, Score: 0.16395
Feature: medial E', Score: 0.12733
Feature: Cr, Score: 0.10277
Feature: LA diameter, Score: 0.10211
Feature: Age, Score: 0.09409
Feature: GFR, Score: 0.08630
Feature: PP, Score: 0.07650
Feature: MAP, Score: 0.07366
Feature: medial a', Score: 0.06723
Feature: LAVI, Score: 0.05757
Feature: CKD stage, Score: 0.02472
Feature: Sex, Score: 0.01560
Feature: AF, Score: 0.00818

### Cleaned Data

In [16]:
X, y, feature_list = convert2np(data_df_clean, lbl_colname, selected_feat=True)

In [17]:
hfpef_rf(X, y, feature_list)

==================================================
Prediction of Death
Best parameters set found on development set:

{'max_depth': 5, 'n_estimators': 100}

Grid scores on development set:

0.451 (+/-0.023) for {'max_depth': 5, 'n_estimators': 100}
0.451 (+/-0.023) for {'max_depth': 5, 'n_estimators': 200}
0.451 (+/-0.023) for {'max_depth': 5, 'n_estimators': 400}
0.451 (+/-0.023) for {'max_depth': 10, 'n_estimators': 100}
0.451 (+/-0.023) for {'max_depth': 10, 'n_estimators': 200}
0.451 (+/-0.023) for {'max_depth': 10, 'n_estimators': 400}
0.451 (+/-0.023) for {'max_depth': 20, 'n_estimators': 100}
0.451 (+/-0.023) for {'max_depth': 20, 'n_estimators': 200}
0.451 (+/-0.023) for {'max_depth': 20, 'n_estimators': 400}

count 0/51
Detailed classification report:

              precision    recall  f1-score   support

           0       0.82      1.00      0.90        42
           1       0.00      0.00      0.00         9

    accuracy                           0.82        51
   macro avg       0.41      0.50      0.45        51
weighted avg       0.68      0.82      0.74        51


Feature: LA diameter, Score: 0.11604
Feature: medial a', Score: 0.11137
Feature: NTProBNP, Score: 0.11052
Feature: medial E', Score: 0.10946
Feature: PP, Score: 0.09054
Feature: MAP, Score: 0.08699
Feature: GFR, Score: 0.08465
Feature: Cr, Score: 0.08345
Feature: Age, Score: 0.08251
Feature: LAVI, Score: 0.08069
Feature: CKD stage, Score: 0.02456
Feature: AF, Score: 0.01401
Feature: Sex, Score: 0.00520
==================================================
Prediction of CV death

C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"

Best parameters set found on development set:

{'max_depth': 5, 'n_estimators': 100}

Grid scores on development set:

0.579 (+/-0.421) for {'max_depth': 5, 'n_estimators': 100}
0.579 (+/-0.421) for {'max_depth': 5, 'n_estimators': 200}
0.579 (+/-0.421) for {'max_depth': 5, 'n_estimators': 400}
0.579 (+/-0.421) for {'max_depth': 10, 'n_estimators': 100}
0.579 (+/-0.421) for {'max_depth': 10, 'n_estimators': 200}
0.579 (+/-0.421) for {'max_depth': 10, 'n_estimators': 400}
0.579 (+/-0.421) for {'max_depth': 20, 'n_estimators': 100}
0.579 (+/-0.421) for {'max_depth': 20, 'n_estimators': 200}
0.579 (+/-0.421) for {'max_depth': 20, 'n_estimators': 400}

C:\Users\HP\miniconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"

count 0/51
Detailed classification report:

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        47
           1       0.00      0.00      0.00         4

    accuracy                           0.92        51
   macro avg       0.46      0.50      0.48        51
weighted avg       0.85      0.92      0.88        51


Feature: Age, Score: 0.12943
Feature: medial E', Score: 0.12845
Feature: NTProBNP, Score: 0.12444
Feature: LA diameter, Score: 0.11596
Feature: Cr, Score: 0.08250
Feature: PP, Score: 0.07949
Feature: medial a', Score: 0.07879
Feature: MAP, Score: 0.07228
Feature: GFR, Score: 0.06640
Feature: LAVI, Score: 0.05549
Feature: CKD stage, Score: 0.02481
Feature: AF, Score: 0.02133
Feature: Sex, Score: 0.02063
==================================================
Prediction of HF hospitalization

C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best parameters set found on development set:

{'max_depth': 5, 'n_estimators': 100}

Grid scores on development set:

0.396 (+/-0.390) for {'max_depth': 5, 'n_estimators': 100}
0.381 (+/-0.255) for {'max_depth': 5, 'n_estimators': 200}
0.383 (+/-0.433) for {'max_depth': 5, 'n_estimators': 400}
0.396 (+/-0.390) for {'max_depth': 10, 'n_estimators': 100}
0.365 (+/-0.206) for {'max_depth': 10, 'n_estimators': 200}
0.351 (+/-0.325) for {'max_depth': 10, 'n_estimators': 400}
0.396 (+/-0.390) for {'max_depth': 20, 'n_estimators': 100}
0.365 (+/-0.206) for {'max_depth': 20, 'n_estimators': 200}
0.351 (+/-0.325) for {'max_depth': 20, 'n_estimators': 400}

count 39/51
Detailed classification report:

              precision    recall  f1-score   support

           0       0.25      0.16      0.19        19
           1       0.59      0.72      0.65        32

    accuracy                           0.51        51
   macro avg       0.42      0.44      0.42        51
weighted avg       0.46      0.51      0.48        51


Feature: medial E', Score: 0.15447
Feature: NTProBNP, Score: 0.13728
Feature: medial a', Score: 0.10955
Feature: MAP, Score: 0.09456
Feature: Cr, Score: 0.09413
Feature: PP, Score: 0.08173
Feature: Age, Score: 0.08112
Feature: LAVI, Score: 0.06071
Feature: GFR, Score: 0.05991
Feature: LA diameter, Score: 0.05736
Feature: CKD stage, Score: 0.03078
Feature: Sex, Score: 0.02820
Feature: AF, Score: 0.01021

##  Neural Networks

In [18]:
from sklearn.neural_network import MLPClassifier

In [19]:
def hfpef_ann(X, y, feature_list):
    # Set the parameters by cross-validation
    tuned_parameters = [{'hidden_layer_sizes': [(20,20,20), (100),(20,20)]}]

    ann = MLPClassifier(random_state=0)

    for i in range(y.shape[1]):
        print('==================================================')
        print('Prediction of ' + lbl_colname[i])

        y_true = y[:,i]

        clf = GridSearchCV(ann, tuned_parameters, scoring='f1_macro', cv=5)
        clf.fit(X, y_true)

        print("Best parameters set found on development set:")
        print()
        print(clf.best_params_)
        print()
        print("Grid scores on development set:")
        print()
        means = clf.cv_results_['mean_test_score']
        stds = clf.cv_results_['std_test_score']
        for mean, std, params in zip(means, stds, clf.cv_results_['params']):
            print("%0.3f (+/-%0.03f) for %r"
                  % (mean, std * 2, params))
        print()

        y_pred = cross_val_predict(clf.best_estimator_, X, y_true, cv=5)

        print(f"count {sum(y_pred)}/{len(y_pred)}")
        print("Detailed classification report:")
        print()
        print(classification_report(y_true, y_pred))
        print()

### All Features

In [20]:
X, y, feature_list = convert2np(data_df, lbl_colname)

In [21]:
hfpef_ann(X, y, feature_list)

==================================================
Prediction of Death
Best parameters set found on development set:

{'hidden_layer_sizes': (20, 20, 20)}

Grid scores on development set:

0.455 (+/-0.149) for {'hidden_layer_sizes': (20, 20, 20)}
0.430 (+/-0.011) for {'hidden_layer_sizes': 100}
0.408 (+/-0.044) for {'hidden_layer_sizes': (20, 20)}

count 22/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.74      0.76      0.75        74
           1       0.18      0.17      0.17        24

    accuracy                           0.61        98
   macro avg       0.46      0.46      0.46        98
weighted avg       0.60      0.61      0.61        98


==================================================
Prediction of CV death
Best parameters set found on development set:

{'hidden_layer_sizes': (20, 20, 20)}

Grid scores on development set:

0.507 (+/-0.149) for {'hidden_layer_sizes': (20, 20, 20)}
0.479 (+/-0.013) for {'hidden_layer_sizes': 100}
0.479 (+/-0.013) for {'hidden_layer_sizes': (20, 20)}

count 6/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.92      0.94      0.93        90
           1       0.17      0.12      0.14         8

    accuracy                           0.88        98
   macro avg       0.55      0.53      0.54        98
weighted avg       0.86      0.88      0.87        98


==================================================
Prediction of HF hospitalization
Best parameters set found on development set:

{'hidden_layer_sizes': 100}

Grid scores on development set:

0.612 (+/-0.137) for {'hidden_layer_sizes': (20, 20, 20)}
0.645 (+/-0.152) for {'hidden_layer_sizes': 100}
0.544 (+/-0.387) for {'hidden_layer_sizes': (20, 20)}

count 52/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.59      0.66      0.62        41
           1       0.73      0.67      0.70        57

    accuracy                           0.66        98
   macro avg       0.66      0.66      0.66        98
weighted avg       0.67      0.66      0.67        98

### Selected Features

In [22]:
X, y, feature_list = convert2np(data_df, lbl_colname, selected_feat=True)

In [23]:
hfpef_ann(X, y, feature_list)

==================================================
Prediction of Death
Best parameters set found on development set:

{'hidden_layer_sizes': 100}

Grid scores on development set:

0.408 (+/-0.165) for {'hidden_layer_sizes': (20, 20, 20)}
0.427 (+/-0.004) for {'hidden_layer_sizes': 100}
0.374 (+/-0.124) for {'hidden_layer_sizes': (20, 20)}

count 1/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.75      0.99      0.85        74
           1       0.00      0.00      0.00        24

    accuracy                           0.74        98
   macro avg       0.38      0.49      0.43        98
weighted avg       0.57      0.74      0.64        98


==================================================
Prediction of CV death
Best parameters set found on development set:

{'hidden_layer_sizes': 100}

Grid scores on development set:

0.467 (+/-0.021) for {'hidden_layer_sizes': (20, 20, 20)}
0.479 (+/-0.013) for {'hidden_layer_sizes': 100}
0.479 (+/-0.013) for {'hidden_layer_sizes': (20, 20)}

count 0/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        90
           1       0.00      0.00      0.00         8

    accuracy                           0.92        98
   macro avg       0.46      0.50      0.48        98
weighted avg       0.84      0.92      0.88        98


==================================================
Prediction of HF hospitalization

C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best parameters set found on development set:

{'hidden_layer_sizes': 100}

Grid scores on development set:

0.488 (+/-0.116) for {'hidden_layer_sizes': (20, 20, 20)}
0.591 (+/-0.214) for {'hidden_layer_sizes': 100}
0.446 (+/-0.172) for {'hidden_layer_sizes': (20, 20)}

count 67/98
Detailed classification report:

              precision    recall  f1-score   support

           0       0.58      0.44      0.50        41
           1       0.66      0.77      0.71        57

    accuracy                           0.63        98
   macro avg       0.62      0.61      0.60        98
weighted avg       0.62      0.63      0.62        98

### Cleaned Data

In [24]:
X, y, feature_list = convert2np(data_df_clean, lbl_colname, selected_feat=True)

In [25]:
hfpef_ann(X, y, feature_list)

==================================================
Prediction of Death
Best parameters set found on development set:

{'hidden_layer_sizes': (20, 20, 20)}

Grid scores on development set:

0.554 (+/-0.324) for {'hidden_layer_sizes': (20, 20, 20)}
0.451 (+/-0.023) for {'hidden_layer_sizes': 100}
0.451 (+/-0.023) for {'hidden_layer_sizes': (20, 20)}

count 6/51
Detailed classification report:

              precision    recall  f1-score   support

           0       0.84      0.90      0.87        42
           1       0.33      0.22      0.27         9

    accuracy                           0.78        51
   macro avg       0.59      0.56      0.57        51
weighted avg       0.75      0.78      0.77        51


==================================================
Prediction of CV death

C:\Users\HP\miniconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"

Best parameters set found on development set:

{'hidden_layer_sizes': 100}

Grid scores on development set:

0.422 (+/-0.512) for {'hidden_layer_sizes': (20, 20, 20)}
0.579 (+/-0.421) for {'hidden_layer_sizes': 100}
0.579 (+/-0.421) for {'hidden_layer_sizes': (20, 20)}

count 0/51
Detailed classification report:

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        47
           1       0.00      0.00      0.00         4

    accuracy                           0.92        51
   macro avg       0.46      0.50      0.48        51
weighted avg       0.85      0.92      0.88        51


==================================================
Prediction of HF hospitalization

C:\Users\HP\miniconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best parameters set found on development set:

{'hidden_layer_sizes': 100}

Grid scores on development set:

0.445 (+/-0.163) for {'hidden_layer_sizes': (20, 20, 20)}
0.466 (+/-0.179) for {'hidden_layer_sizes': 100}
0.271 (+/-0.043) for {'hidden_layer_sizes': (20, 20)}

count 37/51
Detailed classification report:

              precision    recall  f1-score   support

           0       0.43      0.32      0.36        19
           1       0.65      0.75      0.70        32

    accuracy                           0.59        51
   macro avg       0.54      0.53      0.53        51
weighted avg       0.57      0.59      0.57        51